---
namespace: k0rdent
name: core
version: 0.0.1
readme: README.md
authors:
  - Dmitry Ukov <dukov@mirantis.com>
description: Collection with ansible automation for k0rdent
license: GPL-3.0-or-later
tags:
  - k0rdent
dependencies: {}
repository: https://github.com/dukov/ansible-collections-k0rdent
documentation: http://docs.example.com
homepage: http://example.com
issues: https://github.com/dukov/ansible-collections-k0rdent/issues
build_ignore:
  - "*.tar.gz"
  - build_artifact
  - ci
  - galaxy.yml.in
  - setup.cfg
  - test-requirements*
  - tests
  - tools
  - tox.ini
  - .gitignore
  - .gitreview
  - .zuul.yaml
  - .pytest_cache
  - importer_result.json
  - .tox
  - .env
  - .vscode
  - ansible_collections_openstack.egg-info
  - changelogs
